code: detect code path more smartly

diff --git a/bin/code b/bin/code
--- a/bin/code
+++ b/bin/code
@@ -7,6 +7,19 @@ if [ $# -ne 1 ] && [ $# -ne 2 ] && [ $# -ne 3 ]; then
 	exit 1
 fi
 
+CODE_PATH=
+for path in /code "$HOME/Code" "$HOME/code"; do
+    if [ -d "$path" ]; then
+        CODE_PATH=$path
+        break
+    fi
+done
+
+if [ -z "$CODE_PATH" ]; then
+    echo "ERROR: can't find valid code path"
+    exit 1
+fi
+
 CACHE_TXT="$HOME/.cache/.code.cache.txt"
 CACHE_MD5="$HOME/.cache/.code.cache.md5sum"
 LAST_BASE="$HOME/.cache/.code.last"
@@ -36,7 +49,7 @@ function create_cache() {
 	# This magical find command will find a directory maching the
 	# codebase's name, which also has a .git subdirectory. It then
 	# prints the path of the directory.
-	find -L /code/ \
+	find -L $CODE_PATH/ \
 		-maxdepth 5 \
 		-type d \
 		-path "*/.git" \
@@ -48,7 +61,7 @@ if [ -f "$CACHE_TXT" ] && [ -f "$CACHE_MD5" ]; then
 
 	# check that the listing is still valid
 	cursum=$(cat "$CACHE_MD5")
-	newsum=$(tree -d -L 4 /code | md5sum | cut -f 1 -d ' ')
+	newsum=$(tree -d -L 4 /$CODE_PATH | md5sum | cut -f 1 -d ' ')
 	if [ "$cursum" != "$newsum" ]; then
 		create_cache
 		echo "$newsum" > "$CACHE_MD5"
