domssh: increase invalid ip timeout to 15s

diff --git a/bin/domssh b/bin/domssh
--- a/bin/domssh
+++ b/bin/domssh
@@ -138,7 +138,8 @@ if [[ -z $ip ]] || ! ping -c 1 -W 1 $ip &>/dev/null; then
 
 	# Wait until a valid IP address is produced
 	i=0
-	while [ $i -lt 10 ]; do
+	timeout=15
+	while [ $i -lt $timeout ]; do
 
 		ip=$(get_domain_ip $dom)
 		if [ $? != 0 ]; then
@@ -158,9 +159,9 @@ if [[ -z $ip ]] || ! ping -c 1 -W 1 $ip &>/dev/null; then
 		fi
 	done
 
-	if [ $i -eq 10 ]; then
+	if [ $i -eq $timeout ]; then
 		echo
-		echo "Domain IP has been invalid for more than 10s" >&2
+		echo "Domain IP has been invalid for more than ${timeout}s" >&2
 		exit 1
 	fi
 fi
